name: Demo
on:
 workflow_dispatch:
jobs:
  hello-world:
   runs-on: ${{ matrix.os }}
   strategy:
     
     fail-fast: true  # Stop all matrix jobs if any job fails
     matrix:
      os: [ubuntu-latest]
      python-version: [3.8, 3.9, 3.12, 3.11]
      
   steps:
      - name: Checkout
        uses: actions/checkout@v3
       
   # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies (if needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # Run the Python script
      - name: Run Hello World script
        run: python hello-world.py
